const verben = [
  // ei → ie
  { infinitiv: "bleiben",       praeteritum: "blieb",          perfekt: "ist geblieben",          gruppe: "ei → ie" },
  { infinitiv: "scheinen",      praeteritum: "schien",         perfekt: "hat geschienen",         gruppe: "ei → ie" },
  { infinitiv: "schreiben",     praeteritum: "schrieb",        perfekt: "hat geschrieben",        gruppe: "ei → ie" },
  { infinitiv: "schweigen",     praeteritum: "schwieg",        perfekt: "hat geschwiegen",        gruppe: "ei → ie" },
  { infinitiv: "steigen",       praeteritum: "stieg",          perfekt: "ist gestiegen",          gruppe: "ei → ie" },
  { infinitiv: "streichen",     praeteritum: "strich",         perfekt: "hat gestrichen",         gruppe: "ei → ie" },
  { infinitiv: "streiten",      praeteritum: "stritt",         perfekt: "hat gestritten",         gruppe: "ei → ie" },
  { infinitiv: "treiben",       praeteritum: "trieb",          perfekt: "hat getrieben",          gruppe: "ei → ie" },
  { infinitiv: "weisen",        praeteritum: "wies",           perfekt: "hat gewiesen",           gruppe: "ei → ie" },
  { infinitiv: "beißen",        praeteritum: "biss",           perfekt: "hat gebissen",           gruppe: "ei → ie" },
  { infinitiv: "reiten",        praeteritum: "ritt",           perfekt: "ist geritten",           gruppe: "ei → ie" },
  { infinitiv: "schneiden",     praeteritum: "schnitt",        perfekt: "hat geschnitten",        gruppe: "ei → ie" },
  { infinitiv: "schreien",      praeteritum: "schrie",         perfekt: "hat geschrien",          gruppe: "ei → ie" },
  { infinitiv: "leiden",        praeteritum: "litt",           perfekt: "hat gelitten",           gruppe: "ei → ie" },
  { infinitiv: "gleichen",      praeteritum: "glich",          perfekt: "hat geglichen",          gruppe: "ei → ie" },
  { infinitiv: "greifen",       praeteritum: "griff",          perfekt: "hat gegriffen",          gruppe: "ei → ie" },
  { infinitiv: "leihen",        praeteritum: "lieh",           perfekt: "hat geliehen",           gruppe: "ei → ie" },

  // i → a
  { infinitiv: "beginnen",      praeteritum: "begann",         perfekt: "hat begonnen",           gruppe: "i → a"   },
  { infinitiv: "finden",        praeteritum: "fand",           perfekt: "hat gefunden",           gruppe: "i → a"   },
  { infinitiv: "gewinnen",      praeteritum: "gewann",         perfekt: "hat gewonnen",           gruppe: "i → a"   },
  { infinitiv: "klingen",       praeteritum: "klang",          perfekt: "hat geklungen",          gruppe: "i → a"   },
  { infinitiv: "ringen",        praeteritum: "rang",           perfekt: "hat gerungen",           gruppe: "i → a"   },
  { infinitiv: "singen",        praeteritum: "sang",           perfekt: "hat gesungen",           gruppe: "i → a"   },
  { infinitiv: "sinken",        praeteritum: "sank",           perfekt: "ist gesunken",           gruppe: "i → a"   },
  { infinitiv: "springen",      praeteritum: "sprang",         perfekt: "ist gesprungen",         gruppe: "i → a"   },
  { infinitiv: "stinken",       praeteritum: "stank",          perfekt: "hat gestunken",          gruppe: "i → a"   },
  { infinitiv: "trinken",       praeteritum: "trank",          perfekt: "hat getrunken",          gruppe: "i → a"   },
  { infinitiv: "zwingen",       praeteritum: "zwang",          perfekt: "hat gezwungen",          gruppe: "i → a"   },
  { infinitiv: "gelingen",      praeteritum: "gelang",         perfekt: "ist gelungen",           gruppe: "i → a"   },
  { infinitiv: "verschwinden",  praeteritum: "verschwand",     perfekt: "ist verschwunden",       gruppe: "i → a"   },

  // ie → o
  { infinitiv: "fliegen",       praeteritum: "flog",           perfekt: "ist geflogen",           gruppe: "ie → o"  },
  { infinitiv: "fließen",       praeteritum: "floss",          perfekt: "ist geflossen",          gruppe: "ie → o"  },
  { infinitiv: "frieren",       praeteritum: "fror",           perfekt: "ist gefroren",           gruppe: "ie → o"  },
  { infinitiv: "genießen",      praeteritum: "genoss",         perfekt: "hat genossen",           gruppe: "ie → o"  },
  { infinitiv: "gießen",        praeteritum: "goss",           perfekt: "hat gegossen",           gruppe: "ie → o"  },
  { infinitiv: "riechen",       praeteritum: "roch",           perfekt: "hat gerochen",           gruppe: "ie → o"  },
  { infinitiv: "schießen",      praeteritum: "schoss",         perfekt: "hat geschossen",         gruppe: "ie → o"  },
  { infinitiv: "schließen",     praeteritum: "schloss",        perfekt: "hat geschlossen",        gruppe: "ie → o"  },
  { infinitiv: "verlieren",     praeteritum: "verlor",         perfekt: "hat verloren",           gruppe: "ie → o"  },
  { infinitiv: "ziehen",        praeteritum: "zog",            perfekt: "hat/ist gezogen",        gruppe: "ie → o"  },
  { infinitiv: "lügen",         praeteritum: "log",            perfekt: "hat gelogen",            gruppe: "ie → o"  },
  { infinitiv: "wiegen",        praeteritum: "wog",            perfekt: "hat gewogen",            gruppe: "ie → o"  },
  { infinitiv: "biegen",        praeteritum: "bog",            perfekt: "hat/ist gebogen",        gruppe: "ie → o"  },
  { infinitiv: "bieten",        praeteritum: "bot",            perfekt: "hat geboten",            gruppe: "ie → o"  },
  { infinitiv: "verleihen",     praeteritum: "verlieh",        perfekt: "hat verliehen",          gruppe: "ie → o"  },

  // e → a
  { infinitiv: "brechen",       praeteritum: "brach",          perfekt: "hat/ist gebrochen",      gruppe: "e → a"   },
  { infinitiv: "empfehlen",     praeteritum: "empfahl",        perfekt: "hat empfohlen",          gruppe: "e → a"   },
  { infinitiv: "erschrecken",   praeteritum: "erschrak",       perfekt: "ist erschrocken",        gruppe: "e → a"   },
  { infinitiv: "essen",         praeteritum: "aß",             perfekt: "hat gegessen",           gruppe: "e → a"   },
  { infinitiv: "fressen",       praeteritum: "fraß",           perfekt: "hat gefressen",          gruppe: "e → a"   },
  { infinitiv: "geben",         praeteritum: "gab",            perfekt: "hat gegeben",            gruppe: "e → a"   },
  { infinitiv: "gelten",        praeteritum: "galt",           perfekt: "hat gegolten",           gruppe: "e → a"   },
  { infinitiv: "geschehen",     praeteritum: "geschah",        perfekt: "ist geschehen",          gruppe: "e → a"   },
  { infinitiv: "lesen",         praeteritum: "las",            perfekt: "hat gelesen",            gruppe: "e → a"   },
  { infinitiv: "messen",        praeteritum: "maß",            perfekt: "hat gemessen",           gruppe: "e → a"   },
  { infinitiv: "nehmen",        praeteritum: "nahm",           perfekt: "hat genommen",           gruppe: "e → a"   },
  { infinitiv: "sehen",         praeteritum: "sah",            perfekt: "hat gesehen",            gruppe: "e → a"   },
  { infinitiv: "sprechen",      praeteritum: "sprach",         perfekt: "hat gesprochen",         gruppe: "e → a"   },
  { infinitiv: "stehlen",       praeteritum: "stahl",          perfekt: "hat gestohlen",          gruppe: "e → a"   },
  { infinitiv: "treffen",       praeteritum: "traf",           perfekt: "hat getroffen",          gruppe: "e → a"   },
  { infinitiv: "vergessen",     praeteritum: "vergaß",         perfekt: "hat vergessen",          gruppe: "e → a"   },
  { infinitiv: "empfangen",     praeteritum: "empfing",        perfekt: "hat empfangen",          gruppe: "e → a"   },

  // a → u
  { infinitiv: "backen",        praeteritum: "buk",            perfekt: "hat gebacken",           gruppe: "a → u"   },
  { infinitiv: "einladen",      praeteritum: "lud ein",        perfekt: "hat eingeladen",         gruppe: "a → u"   },
  { infinitiv: "erfahren",      praeteritum: "erfuhr",         perfekt: "hat erfahren",           gruppe: "a → u"   },
  { infinitiv: "fahren",        praeteritum: "fuhr",           perfekt: "ist gefahren",           gruppe: "a → u"   },
  { infinitiv: "laden",         praeteritum: "lud",            perfekt: "hat geladen",            gruppe: "a → u"   },
  { infinitiv: "schlagen",      praeteritum: "schlug",         perfekt: "hat geschlagen",         gruppe: "a → u"   },
  { infinitiv: "tragen",        praeteritum: "trug",           perfekt: "hat getragen",           gruppe: "a → u"   },
  { infinitiv: "wachsen",       praeteritum: "wuchs",          perfekt: "ist gewachsen",          gruppe: "a → u"   },
  { infinitiv: "waschen",       praeteritum: "wusch",          perfekt: "hat gewaschen",          gruppe: "a → u"   },
  { infinitiv: "graben",        praeteritum: "grub",           perfekt: "hat gegraben",           gruppe: "a → u"   },

  // a → ie
  { infinitiv: "fallen",        praeteritum: "fiel",           perfekt: "ist gefallen",           gruppe: "a → ie"  },
  { infinitiv: "gefallen",      praeteritum: "gefiel",         perfekt: "hat gefallen",           gruppe: "a → ie"  },
  { infinitiv: "halten",        praeteritum: "hielt",          perfekt: "hat gehalten",           gruppe: "a → ie"  },
  { infinitiv: "hängen",        praeteritum: "hing",           perfekt: "hat gehangen",           gruppe: "a → ie"  },
  { infinitiv: "lassen",        praeteritum: "ließ",           perfekt: "hat gelassen",           gruppe: "a → ie"  },
  { infinitiv: "laufen",        praeteritum: "lief",           perfekt: "ist gelaufen",           gruppe: "a → ie"  },
  { infinitiv: "raten",         praeteritum: "riet",           perfekt: "hat geraten",            gruppe: "a → ie"  },
  { infinitiv: "rufen",         praeteritum: "rief",           perfekt: "hat gerufen",            gruppe: "a → ie"  },
  { infinitiv: "schlafen",      praeteritum: "schlief",        perfekt: "hat geschlafen",         gruppe: "a → ie"  },
  { infinitiv: "stoßen",        praeteritum: "stieß",          perfekt: "hat/ist gestoßen",       gruppe: "a → ie"  },

  // e → o
  { infinitiv: "erschaffen",    praeteritum: "erschuf",        perfekt: "hat erschaffen",         gruppe: "e → o"   },
  { infinitiv: "gebären",       praeteritum: "gebar",          perfekt: "hat geboren",            gruppe: "e → o"   },
  { infinitiv: "helfen",        praeteritum: "half",           perfekt: "hat geholfen",           gruppe: "e → o"   },
  { infinitiv: "sterben",       praeteritum: "starb",          perfekt: "ist gestorben",          gruppe: "e → o"   },
  { infinitiv: "verderben",     praeteritum: "verdarb",        perfekt: "hat/ist verdorben",      gruppe: "e → o"   },
  { infinitiv: "werfen",        praeteritum: "warf",           perfekt: "hat geworfen",           gruppe: "e → o"   },
  { infinitiv: "erwerben",      praeteritum: "erwarb",         perfekt: "hat erworben",           gruppe: "e → o"   },

  // Mischverben
  { infinitiv: "bringen",       praeteritum: "brachte",        perfekt: "hat gebracht",           gruppe: "Mischverben" },
  { infinitiv: "denken",        praeteritum: "dachte",         perfekt: "hat gedacht",            gruppe: "Mischverben" },
  { infinitiv: "kennen",        praeteritum: "kannte",         perfekt: "hat gekannt",            gruppe: "Mischverben" },
  { infinitiv: "nennen",        praeteritum: "nannte",         perfekt: "hat genannt",            gruppe: "Mischverben" },
  { infinitiv: "rennen",        praeteritum: "rannte",         perfekt: "ist gerannt",            gruppe: "Mischverben" },
  { infinitiv: "verbringen",    praeteritum: "verbrachte",     perfekt: "hat verbracht",          gruppe: "Mischverben" },
  { infinitiv: "wissen",        praeteritum: "wusste",         perfekt: "hat gewusst",            gruppe: "Mischverben" },
  { infinitiv: "brennen",       praeteritum: "brannte",        perfekt: "hat gebrannt",           gruppe: "Mischverben" },
  { infinitiv: "senden",        praeteritum: "sandte",         perfekt: "hat gesandt",            gruppe: "Mischverben" },

  // Besondere
  { infinitiv: "gehen",         praeteritum: "ging",           perfekt: "ist gegangen",           gruppe: "Besondere" },
  { infinitiv: "haben",         praeteritum: "hatte",          perfekt: "hat gehabt",             gruppe: "Besondere" },
  { infinitiv: "kommen",        praeteritum: "kam",            perfekt: "ist gekommen",           gruppe: "Besondere" },
  { infinitiv: "liegen",        praeteritum: "lag",            perfekt: "hat/ist gelegen",        gruppe: "Besondere" },
  { infinitiv: "sein",          praeteritum: "war",            perfekt: "ist gewesen",            gruppe: "Besondere" },
  { infinitiv: "sitzen",        praeteritum: "saß",            perfekt: "hat gesessen",           gruppe: "Besondere" },
  { infinitiv: "stehen",        praeteritum: "stand",          perfekt: "hat/ist gestanden",      gruppe: "Besondere" },
  { infinitiv: "tun",           praeteritum: "tat",            perfekt: "hat getan",              gruppe: "Besondere" },
  { infinitiv: "werden",        praeteritum: "wurde",          perfekt: "ist geworden",           gruppe: "Besondere" },

  // Modalverben
  { infinitiv: "dürfen",        praeteritum: "durfte",         perfekt: "hat gedurft",            gruppe: "Modalverben" },
  { infinitiv: "können",        praeteritum: "konnte",         perfekt: "hat gekonnt",            gruppe: "Modalverben" },
  { infinitiv: "mögen",         praeteritum: "mochte",         perfekt: "hat gemocht",            gruppe: "Modalverben" },
  { infinitiv: "möchten",       praeteritum: "mochte",         perfekt: "hat gemocht",            gruppe: "Modalverben" },
  { infinitiv: "müssen",        praeteritum: "musste",         perfekt: "hat gemusst",            gruppe: "Modalverben" },
  { infinitiv: "sollen",        praeteritum: "sollte",         perfekt: "hat gesollt",            gruppe: "Modalverben" },
  { infinitiv: "wollen",        praeteritum: "wollte",         perfekt: "hat gewollt",            gruppe: "Modalverben" },
];