const verben = [
  // ei → ie
  { infinitiv: "bleiben", praeteritum: "blieb", perfekt: "ist geblieben", gruppe: "ei → ie", uk: "залишатися", en: "to stay" },
  { infinitiv: "scheinen", praeteritum: "schien", perfekt: "hat geschienen", gruppe: "ei → ie", uk: "світити", en: "to shine" },
  { infinitiv: "schreiben", praeteritum: "schrieb", perfekt: "hat geschrieben", gruppe: "ei → ie", uk: "писати", en: "to write" },
  { infinitiv: "schweigen", praeteritum: "schwieg", perfekt: "hat geschwiegen", gruppe: "ei → ie", uk: "мовчати", en: "to be silent" },
  { infinitiv: "steigen", praeteritum: "stieg", perfekt: "ist gestiegen", gruppe: "ei → ie", uk: "підніматися", en: "to climb" },
  { infinitiv: "streichen", praeteritum: "strich", perfekt: "hat gestrichen", gruppe: "ei → ie", uk: "малювати/креслити", en: "to paint/stroke" },
  { infinitiv: "streiten", praeteritum: "stritt", perfekt: "hat gestritten", gruppe: "ei → ie", uk: "сперечатися", en: "to argue" },
  { infinitiv: "treiben", praeteritum: "trieb", perfekt: "hat getrieben", gruppe: "ei → ie", uk: "гнати/займатися", en: "to drive/do" },
  { infinitiv: "weisen", praeteritum: "wies", perfekt: "hat gewiesen", gruppe: "ei → ie", uk: "вказувати", en: "to point" },
  { infinitiv: "beißen", praeteritum: "biss", perfekt: "hat gebissen", gruppe: "ei → ie", uk: "кусати", en: "to bite" },
  { infinitiv: "reiten", praeteritum: "ritt", perfekt: "ist geritten", gruppe: "ei → ie", uk: "їздити верхи", en: "to ride" },
  { infinitiv: "schneiden", praeteritum: "schnitt", perfekt: "hat geschnitten", gruppe: "ei → ie", uk: "різати", en: "to cut" },
  { infinitiv: "schreien", praeteritum: "schrie", perfekt: "hat geschrien", gruppe: "ei → ie", uk: "кричати", en: "to scream" },
  { infinitiv: "leiden", praeteritum: "litt", perfekt: "hat gelitten", gruppe: "ei → ie", uk: "страждати", en: "to suffer" },
  { infinitiv: "gleichen", praeteritum: "glich", perfekt: "hat geglichen", gruppe: "ei → ie", uk: "бути схожим", en: "to resemble" },
  { infinitiv: "greifen", praeteritum: "griff", perfekt: "hat gegriffen", gruppe: "ei → ie", uk: "хапати", en: "to grab" },
  { infinitiv: "leihen", praeteritum: "lieh", perfekt: "hat geliehen", gruppe: "ei → ie", uk: "позичати", en: "to lend" },

  // i → a
  { infinitiv: "beginnen", praeteritum: "begann", perfekt: "hat begonnen", gruppe: "i → a", uk: "починати", en: "to begin" },
  { infinitiv: "finden", praeteritum: "fand", perfekt: "hat gefunden", gruppe: "i → a", uk: "знаходити", en: "to find" },
  { infinitiv: "gewinnen", praeteritum: "gewann", perfekt: "hat gewonnen", gruppe: "i → a", uk: "вигравати", en: "to win" },
  { infinitiv: "klingen", praeteritum: "klang", perfekt: "hat geklungen", gruppe: "i → a", uk: "звучати", en: "to sound" },
  { infinitiv: "ringen", praeteritum: "rang", perfekt: "hat gerungen", gruppe: "i → a", uk: "боротися", en: "to wrestle" },
  { infinitiv: "singen", praeteritum: "sang", perfekt: "hat gesungen", gruppe: "i → a", uk: "співати", en: "to sing" },
  { infinitiv: "sinken", praeteritum: "sank", perfekt: "ist gesunken", gruppe: "i → a", uk: "тонути/падати", en: "to sink" },
  { infinitiv: "springen", praeteritum: "sprang", perfekt: "ist gesprungen", gruppe: "i → a", uk: "стрибати", en: "to jump" },
  { infinitiv: "stinken", praeteritum: "stank", perfekt: "hat gestunken", gruppe: "i → a", uk: "смердіти", en: "to stink" },
  { infinitiv: "trinken", praeteritum: "trank", perfekt: "hat getrunken", gruppe: "i → a", uk: "пити", en: "to drink" },
  { infinitiv: "zwingen", praeteritum: "zwang", perfekt: "hat gezwungen", gruppe: "i → a", uk: "змушувати", en: "to force" },
  { infinitiv: "gelingen", praeteritum: "gelang", perfekt: "ist gelungen", gruppe: "i → a", uk: "вдаватися", en: "to succeed" },
  { infinitiv: "verschwinden", praeteritum: "verschwand", perfekt: "ist verschwunden", gruppe: "i → a", uk: "зникати", en: "to disappear" },

  // ie → o
  { infinitiv: "fliegen", praeteritum: "flog", perfekt: "ist geflogen", gruppe: "ie → o", uk: "літати", en: "to fly" },
  { infinitiv: "fließen", praeteritum: "floss", perfekt: "ist geflossen", gruppe: "ie → o", uk: "текти", en: "to flow" },
  { infinitiv: "frieren", praeteritum: "fror", perfekt: "ist gefroren", gruppe: "ie → o", uk: "мерзнути", en: "to freeze" },
  { infinitiv: "genießen", praeteritum: "genoss", perfekt: "hat genossen", gruppe: "ie → o", uk: "насолоджуватися", en: "to enjoy" },
  { infinitiv: "gießen", praeteritum: "goss", perfekt: "hat gegossen", gruppe: "ie → o", uk: "лити/поливати", en: "to pour" },
  { infinitiv: "riechen", praeteritum: "roch", perfekt: "hat gerochen", gruppe: "ie → o", uk: "нюхати/пахнути", en: "to smell" },
  { infinitiv: "schießen", praeteritum: "schoss", perfekt: "hat geschossen", gruppe: "ie → o", uk: "стріляти", en: "to shoot" },
  { infinitiv: "schließen", praeteritum: "schloss", perfekt: "hat geschlossen", gruppe: "ie → o", uk: "зачиняти", en: "to close" },
  { infinitiv: "verlieren", praeteritum: "verlor", perfekt: "hat verloren", gruppe: "ie → o", uk: "втрачати", en: "to lose" },
  { infinitiv: "ziehen", praeteritum: "zog", perfekt: "hat/ist gezogen", gruppe: "ie → o", uk: "тягнути/переїжджати", en: "to pull/move" },
  { infinitiv: "lügen", praeteritum: "log", perfekt: "hat gelogen", gruppe: "ie → o", uk: "брехати", en: "to lie" },
  { infinitiv: "wiegen", praeteritum: "wog", perfekt: "hat gewogen", gruppe: "ie → o", uk: "важити", en: "to weigh" },
  { infinitiv: "biegen", praeteritum: "bog", perfekt: "hat/ist gebogen", gruppe: "ie → o", uk: "згинати", en: "to bend" },
  { infinitiv: "bieten", praeteritum: "bot", perfekt: "hat geboten", gruppe: "ie → o", uk: "пропонувати", en: "to offer" },
  { infinitiv: "verleihen", praeteritum: "verlieh", perfekt: "hat verliehen", gruppe: "ie → o", uk: "позичати/видавати", en: "to lend/award" },

  // e → a
  { infinitiv: "brechen", praeteritum: "brach", perfekt: "hat/ist gebrochen", gruppe: "e → a", uk: "ламати", en: "to break" },
  { infinitiv: "empfehlen", praeteritum: "empfahl", perfekt: "hat empfohlen", gruppe: "e → a", uk: "рекомендувати", en: "to recommend" },
  { infinitiv: "erschrecken", praeteritum: "erschrak", perfekt: "ist erschrocken", gruppe: "e → a", uk: "лякатися", en: "to be frightened" },
  { infinitiv: "essen", praeteritum: "aß", perfekt: "hat gegessen", gruppe: "e → a", uk: "їсти", en: "to eat" },
  { infinitiv: "fressen", praeteritum: "fraß", perfekt: "hat gefressen", gruppe: "e → a", uk: "жерти", en: "to devour" },
  { infinitiv: "geben", praeteritum: "gab", perfekt: "hat gegeben", gruppe: "e → a", uk: "давати", en: "to give" },
  { infinitiv: "gelten", praeteritum: "galt", perfekt: "hat gegolten", gruppe: "e → a", uk: "діяти/бути дійсним", en: "to be valid" },
  { infinitiv: "geschehen", praeteritum: "geschah", perfekt: "ist geschehen", gruppe: "e → a", uk: "відбуватися", en: "to happen" },
  { infinitiv: "lesen", praeteritum: "las", perfekt: "hat gelesen", gruppe: "e → a", uk: "читати", en: "to read" },
  { infinitiv: "messen", praeteritum: "maß", perfekt: "hat gemessen", gruppe: "e → a", uk: "вимірювати", en: "to measure" },
  { infinitiv: "nehmen", praeteritum: "nahm", perfekt: "hat genommen", gruppe: "e → a", uk: "брати", en: "to take" },
  { infinitiv: "sehen", praeteritum: "sah", perfekt: "hat gesehen", gruppe: "e → a", uk: "бачити", en: "to see" },
  { infinitiv: "sprechen", praeteritum: "sprach", perfekt: "hat gesprochen", gruppe: "e → a", uk: "говорити", en: "to speak" },
  { infinitiv: "stehlen", praeteritum: "stahl", perfekt: "hat gestohlen", gruppe: "e → a", uk: "красти", en: "to steal" },
  { infinitiv: "treffen", praeteritum: "traf", perfekt: "hat getroffen", gruppe: "e → a", uk: "зустрічати", en: "to meet" },
  { infinitiv: "vergessen", praeteritum: "vergaß", perfekt: "hat vergessen", gruppe: "e → a", uk: "забувати", en: "to forget" },
  { infinitiv: "empfangen", praeteritum: "empfing", perfekt: "hat empfangen", gruppe: "e → a", uk: "отримувати", en: "to receive" },

  // a → u
  { infinitiv: "backen", praeteritum: "buk", perfekt: "hat gebacken", gruppe: "a → u", uk: "пекти", en: "to bake" },
  { infinitiv: "einladen", praeteritum: "lud ein", perfekt: "hat eingeladen", gruppe: "a → u", uk: "запрошувати", en: "to invite" },
  { infinitiv: "erfahren", praeteritum: "erfuhr", perfekt: "hat erfahren", gruppe: "a → u", uk: "дізнаватися", en: "to find out" },
  { infinitiv: "fahren", praeteritum: "fuhr", perfekt: "ist gefahren", gruppe: "a → u", uk: "їхати", en: "to drive" },
  { infinitiv: "laden", praeteritum: "lud", perfekt: "hat geladen", gruppe: "a → u", uk: "завантажувати", en: "to load" },
  { infinitiv: "schlagen", praeteritum: "schlug", perfekt: "hat geschlagen", gruppe: "a → u", uk: "бити", en: "to hit" },
  { infinitiv: "tragen", praeteritum: "trug", perfekt: "hat getragen", gruppe: "a → u", uk: "носити", en: "to carry" },
  { infinitiv: "wachsen", praeteritum: "wuchs", perfekt: "ist gewachsen", gruppe: "a → u", uk: "рости", en: "to grow" },
  { infinitiv: "waschen", praeteritum: "wusch", perfekt: "hat gewaschen", gruppe: "a → u", uk: "мити", en: "to wash" },
  { infinitiv: "graben", praeteritum: "grub", perfekt: "hat gegraben", gruppe: "a → u", uk: "копати", en: "to dig" },

  // a → ie
  { infinitiv: "fallen", praeteritum: "fiel", perfekt: "ist gefallen", gruppe: "a → ie", uk: "падати", en: "to fall" },
  { infinitiv: "gefallen", praeteritum: "gefiel", perfekt: "hat gefallen", gruppe: "a → ie", uk: "подобатися", en: "to please" },
  { infinitiv: "halten", praeteritum: "hielt", perfekt: "hat gehalten", gruppe: "a → ie", uk: "тримати", en: "to hold" },
  { infinitiv: "hängen", praeteritum: "hing", perfekt: "hat gehangen", gruppe: "a → ie", uk: "висіти", en: "to hang" },
  { infinitiv: "lassen", praeteritum: "ließ", perfekt: "hat gelassen", gruppe: "a → ie", uk: "залишати/дозволяти", en: "to let/leave" },
  { infinitiv: "laufen", praeteritum: "lief", perfekt: "ist gelaufen", gruppe: "a → ie", uk: "бігти", en: "to run" },
  { infinitiv: "raten", praeteritum: "riet", perfekt: "hat geraten", gruppe: "a → ie", uk: "радити/вгадувати", en: "to advise/guess" },
  { infinitiv: "rufen", praeteritum: "rief", perfekt: "hat gerufen", gruppe: "a → ie", uk: "кликати", en: "to call" },
  { infinitiv: "schlafen", praeteritum: "schlief", perfekt: "hat geschlafen", gruppe: "a → ie", uk: "спати", en: "to sleep" },
  { infinitiv: "stoßen", praeteritum: "stieß", perfekt: "hat/ist gestoßen", gruppe: "a → ie", uk: "штовхати", en: "to push" },

  // e → o
  { infinitiv: "erschaffen", praeteritum: "erschuf", perfekt: "hat erschaffen", gruppe: "e → o", uk: "творити", en: "to create" },
  { infinitiv: "gebären", praeteritum: "gebar", perfekt: "hat geboren", gruppe: "e → o", uk: "народжувати", en: "to give birth" },
  { infinitiv: "helfen", praeteritum: "half", perfekt: "hat geholfen", gruppe: "e → o", uk: "допомагати", en: "to help" },
  { infinitiv: "sterben", praeteritum: "starb", perfekt: "ist gestorben", gruppe: "e → o", uk: "вмирати", en: "to die" },
  { infinitiv: "verderben", praeteritum: "verdarb", perfekt: "hat/ist verdorben", gruppe: "e → o", uk: "псувати", en: "to spoil" },
  { infinitiv: "werfen", praeteritum: "warf", perfekt: "hat geworfen", gruppe: "e → o", uk: "кидати", en: "to throw" },
  { infinitiv: "erwerben", praeteritum: "erwarb", perfekt: "hat erworben", gruppe: "e → o", uk: "здобувати", en: "to acquire" },

  // Mischverben
  { infinitiv: "bringen", praeteritum: "brachte", perfekt: "hat gebracht", gruppe: "Mischverben", uk: "приносити", en: "to bring" },
  { infinitiv: "denken", praeteritum: "dachte", perfekt: "hat gedacht", gruppe: "Mischverben", uk: "думати", en: "to think" },
  { infinitiv: "kennen", praeteritum: "kannte", perfekt: "hat gekannt", gruppe: "Mischverben", uk: "знати", en: "to know" },
  { infinitiv: "nennen", praeteritum: "nannte", perfekt: "hat genannt", gruppe: "Mischverben", uk: "називати", en: "to name" },
  { infinitiv: "rennen", praeteritum: "rannte", perfekt: "ist gerannt", gruppe: "Mischverben", uk: "бігти", en: "to run" },
  { infinitiv: "verbringen", praeteritum: "verbrachte", perfekt: "hat verbracht", gruppe: "Mischverben", uk: "проводити час", en: "to spend time" },
  { infinitiv: "wissen", praeteritum: "wusste", perfekt: "hat gewusst", gruppe: "Mischverben", uk: "знати (факт)", en: "to know (fact)" },
  { infinitiv: "brennen", praeteritum: "brannte", perfekt: "hat gebrannt", gruppe: "Mischverben", uk: "горіти", en: "to burn" },
  { infinitiv: "senden", praeteritum: "sandte", perfekt: "hat gesandt", gruppe: "Mischverben", uk: "надсилати", en: "to send" },

  // Besondere
  { infinitiv: "gehen", praeteritum: "ging", perfekt: "ist gegangen", gruppe: "Besondere", uk: "йти", en: "to go" },
  { infinitiv: "haben", praeteritum: "hatte", perfekt: "hat gehabt", gruppe: "Besondere", uk: "мати", en: "to have" },
  { infinitiv: "kommen", praeteritum: "kam", perfekt: "ist gekommen", gruppe: "Besondere", uk: "приходити", en: "to come" },
  { infinitiv: "liegen", praeteritum: "lag", perfekt: "hat/ist gelegen", gruppe: "Besondere", uk: "лежати", en: "to lie" },
  { infinitiv: "sein", praeteritum: "war", perfekt: "ist gewesen", gruppe: "Besondere", uk: "бути", en: "to be" },
  { infinitiv: "sitzen", praeteritum: "saß", perfekt: "hat gesessen", gruppe: "Besondere", uk: "сидіти", en: "to sit" },
  { infinitiv: "stehen", praeteritum: "stand", perfekt: "hat/ist gestanden", gruppe: "Besondere", uk: "стояти", en: "to stand" },
  { infinitiv: "tun", praeteritum: "tat", perfekt: "hat getan", gruppe: "Besondere", uk: "робити", en: "to do" },
  { infinitiv: "werden", praeteritum: "wurde", perfekt: "ist geworden", gruppe: "Besondere", uk: "ставати", en: "to become" },

  // Modalverben
  { infinitiv: "dürfen", praeteritum: "durfte", perfekt: "hat gedurft", gruppe: "Modalverben", uk: "мати дозвіл", en: "may/to be allowed" },
  { infinitiv: "können", praeteritum: "konnte", perfekt: "hat gekonnt", gruppe: "Modalverben", uk: "могти", en: "can/to be able" },
  { infinitiv: "mögen", praeteritum: "mochte", perfekt: "hat gemocht", gruppe: "Modalverben", uk: "любити", en: "to like" },
  { infinitiv: "möchten", praeteritum: "mochte", perfekt: "hat gemocht", gruppe: "Modalverben", uk: "хотіти", en: "would like" },
  { infinitiv: "müssen", praeteritum: "musste", perfekt: "hat gemusst", gruppe: "Modalverben", uk: "мусити", en: "must/to have to" },
  { infinitiv: "sollen", praeteritum: "sollte", perfekt: "hat gesollt", gruppe: "Modalverben", uk: "повинен", en: "should/to be supposed to" },
  { infinitiv: "wollen", praeteritum: "wollte", perfekt: "hat gewollt", gruppe: "Modalverben", uk: "хотіти", en: "to want" },
];